apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pod-affinity-webhook
  namespace: tekton-pod-affinity
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pod-affinity
subjects:
  - kind: ServiceAccount
    name: tekton-pod-affinity-webhook
    namespace: tekton-pod-affinity
roleRef:
  kind: Role
  name: tekton-pod-affinity-webhook
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pod-affinity-controller
  namespace: tekton-pod-affinity
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pod-affinity
subjects:
  - kind: ServiceAccount
    name: tekton-pod-affinity-controller
    namespace: tekton-pod-affinity
roleRef:
  kind: Role
  name: tekton-pod-affinity-controller
  apiGroup: rbac.authorization.k8s.io
