apiVersion: v1
kind: Secret
metadata:
  name: tekton-pod-affinity-webhook-certs
  namespace: tekton-pod-affinity
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pod-affinity
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod.mutation.webhook.pod-affinity.tekton.dev
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pod-affinity
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: tekton-pod-affinity-webhook
      namespace: tekton-pod-affinity
  failurePolicy: Fail
  sideEffects: None
  name: pod.mutation.webhook.pod-affinity.tekton.dev
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pipelinerun.mutation.webhook.pod-affinity.tekton.dev
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pod-affinity
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: tekton-pod-affinity-webhook
      namespace: tekton-pod-affinity
  failurePolicy: Fail
  sideEffects: None
  name: pipelinerun.mutation.webhook.pod-affinity.tekton.dev

